services:
  web:
    build:
      context: .
      dockerfile: public/Dockerfile
    container_name: web-chall
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app/public
    environment:
      - NODE_ENV=production

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    container_name: web-chall-bot
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app/bot
    environment:
      - NODE_ENV=production
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
